version: "3.9"

services:
  app:  
    build: .
    container_name: study-go
    user: container-user
    volumes:
      - ./:/workspace
      - $HOME/.ssh:/home/container-user/.ssh
    working_dir: /workspace
    tty: true