version: "3.9"

services:
  study-go:  
    image: ghcr.io/kengo-k/dev-golang:202303191300-efbbd41
    container_name: study-go
    volumes:
      - ./:/workspace
      - $HOME/.ssh:/home/container-user/.ssh
    working_dir: /workspace
    tty: true